Repository nerds-run/odious-ado, pull requests merged in 2023-08, with the labels that each got.

#21 dependency fixes
  poetry.lock
  pyproject.toml
Labels: bug, itsals/itsals

#25 Get and Set ADO State
  .gitignore
  .python-version
  Dockerfile
  README.md
  StateMapping.yml
  action.yml
  odious_ado/__init__.py
  odious_ado/cli/__init__.py
  odious_ado/cli/ado.py
  odious_ado/cli/gh.py
  odious_ado/plugins/ado/client.py
  odious_ado/plugins/ado/state.py
  odious_ado/plugins/gh/__init__.py
  odious_ado/plugins/gh/client.py
  odious_ado/plugins/gh/issues.py
  odious_ado/plugins/gh/projects.py
  odious_ado/plugins/gh/pull_requests.py
  odious_ado/settings.py
  odious_ado/text.txt
  pyproject.toml
  requirements.txt
Labels: itsals/EE_Hackathon

#39 Gggg
  odious_ado/cli/ado.py
  odious_ado/plugins/ado/client.py
  odious_ado/plugins/ado/description.py
Labels: itsals/EE_Hackathon

#42 Release&tag
  .github/workflows/create-release.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/docker-image.yml
  .github/workflows/gh-release.yml
  .github/workflows/odious-ado.yml
  .github/workflows/python-package.yml
  .github/workflows/release-drafter.yml
  .python-version
  bin/odious-ado
  odious_ado/settings.py
Labels: PVTI_lADOB3mz7c4AUIpbzgIn0Oo, PVTI_lADOB3mz7c4AUIpbzgIn39U, PVTI_lADOB3mz7c4AUIpbzgIn39c, PVTI_lADOB3mz7c4AUIpbzgIomw0, PVTI_lADOB3mz7c4AUIpbzgIomw8, PVTI_lADOB3mz7c4AUIpbzgIoi88, PVTI_lADOB3mz7c4AUIpbzgIn39w, PVTI_lADOB3mz7c4AUIpbzgIoi9I, PVTI_lADOB3mz7c4AUIpbzgIoi9M, PVTI_lADOB3mz7c4AUIpbzgIoi9Q, PVTI_lADOB3mz7c4AUIpbzgIoi9Y, PVTI_lADOB3mz7c4AUIpbzgIoi9c, PVTI_lADOB3mz7c4AUIpbzgIn7cU, PVTI_lADOB3mz7c4AUIpbzgIoi9g, PVTI_lADOB3mz7c4AUIpbzgIoi90, PVTI_lADOB3mz7c4AUIpbzgIoi98, PVTI_lADOB3mz7c4AUIpbzgIoi-A, PVTI_lADOB3mz7c4AUIpbzgIo9rk
